export const medtechWorklistMock = [
  {
    id: "LAB-1001",
    patientId: "PT001",
    patientName: "Dela Cruz, Juan",
    testType: "CBC",
    priority: "STAT",
    status: "Pending", // Pending | Processing | Ready | Released
    dateRequested: "2026-02-05 08:45",
  },
  {
    id: "LAB-1002",
    patientId: "PT002",
    patientName: "Santos, Maria",
    testType: "Urinalysis",
    priority: "Routine",
    status: "Processing",
    dateRequested: "2026-02-05 09:10",
  },
  {
    id: "LAB-1003",
    patientId: "PT003",
    patientName: "Reyes, Pedro",
    testType: "FBS",
    priority: "Routine",
    status: "Ready",
    dateRequested: "2026-02-05 09:30",
  },
  {
    id: "LAB-1004",
    patientId: "PT004",
    patientName: "Lim, Ana",
    testType: "Lipid Panel",
    priority: "Routine",
    status: "Released",
    dateRequested: "2026-02-05 10:05",
  },
  {
    id: "LAB-1005",
    patientId: "PT005",
    patientName: "Garcia, Noel",
    testType: "CBC",
    priority: "Routine",
    status: "Ready",
    dateRequested: "2026-02-05 10:30",
  },
];
